### ISSUE TITLE
[FEAT] QR 뷰 

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#136]
# 👀 이슈 (issue)

QR뷰에서 명함 뷰를 dismiss하더라도 다시 QR이 시작되게 해보시오. (5점)
단, 델리게이트 처리를 해야한다.

# 🚀 to-do

- [x] restartQR delegate 만들기

**Comment by hyun99999** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ5점
